events { worker_connections 1024; }

http {
  resolver 127.0.0.11 valid=5s ipv6=off;

  upstream patient_service   { server patient-service:3000; }
  upstream heart_rate_service { server heart-rate-service:3000; }
  upstream analytics_service  { server analytics-service:3000; }
  upstream frontend_app       { server frontend:80; }

  server {
    listen 80;

    location /api/patients {
      proxy_pass http://patient_service/patients;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/heart-rate {
      proxy_pass http://heart_rate_service/heart-rate;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/analytics {
      proxy_pass http://analytics_service/analytics;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      proxy_pass http://frontend_app;
      proxy_set_header Host $host;
    }
  }
}
